### ISSUE TITLE
求解

### ISSUE THREAD

**Issue by qzm4228** [MoonBcmTools/FuckMaoNemo#1]
![Screenshot_2024-12-15-01-20-56-731_com.codemao.nemo.jpg](https://github.com/user-attachments/assets/55d846d3-6ffc-4e8e-8a03-8da639d9be7e)

你能动手么😅😅😅

**Comment by MoonLeeeaf** [comment]
> [图片]
> 
> 你能动手么😅😅😅

@qzm4228 我怎么知道你怎么驾崩的 我都退毛半个月了我知道什么😅😅😅

**Comment by MoonLeeeaf** [comment]
@qzm4228 差点没看懂
步骤: 用探月srbc登录 然后抓包获取WorkId就行了
我已经退毛了 我那个号崩殂之后就用的这个方法获取的全作品
一般找你需要的就好了 如果要全作品 得稍微动点手来写脚本批量获取 频率不要太快
